// Assembly Mayreni, Version 1.0.0.0

[assembly: System.Reflection.AssemblyTrademark("")]
[assembly: System.Windows.ThemeInfo(System.Windows.ResourceDictionaryLocation.None, System.Windows.ResourceDictionaryLocation.SourceAssembly)]
[assembly: System.Reflection.AssemblyCopyright("Copyright \x00a9 ICodeZone  2010")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Reflection.AssemblyFileVersion("1.0.0.0")]
[assembly: System.Resources.NeutralResourcesLanguage("hy")]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.DisableOptimizations | System.Diagnostics.DebuggableAttribute.DebuggingModes.EnableEditAndContinue | System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints | System.Diagnostics.DebuggableAttribute.DebuggingModes.Default)]
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows=true)]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFile("shiraz2original.wav")]
[assembly: System.Reflection.AssemblyProduct("Mayreni")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFile("finalalexander.mp3")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFile("garnanamoodmp3.wav")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFile("ghazarosoriginal.mp3")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFile("hayastaninmp3.mp3")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFile("hayoxlerneroommp3.mp3")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFile("hayoxlerneroomoriginalmp3.wav")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFile("hishoghootunmp3original.mp3")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFile("hrajeshdmp3original.mp3")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFile("inknaheraxoomoriginal.mp3")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFile("ktakoriginal.wav")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFile("mp3.wav")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFile("mp3final.wav")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFile("mp3original.wav")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFile("my%20movie.wmv")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFile("s.wav")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFile("sermp3original.mp3")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFile("bb.wav")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFile("shirazoriginal.wav")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFile("shirazoriginal6.wav")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFile("silvabiography.mp3")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFile("stonhange.wmv")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFile("teryanoriginal.wav")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFile("toomanyan1.wav")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFile("toomanyanoriginal.wav")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFile("untitled.mp3")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFile("xankootun.wma")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFile("xnorkoriginal.mp3")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFile("yeghisheoriginal.mp3")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFile("yesimanooshhayastanioriginal.mp3")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFile("zoryanoriginal.wav")]
[assembly: System.Reflection.AssemblyTitle("Mayreni")]
[assembly: System.Reflection.AssemblyDescription("ArmenianHistory")]
[assembly: System.Reflection.AssemblyConfiguration("")]
[assembly: System.Reflection.AssemblyCompany("ICodeZone")]

